### ISSUE TITLE
[FEATURE] Yaml configuration

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#180]
## Expected Behavior
A simple deployment should be configurable with Yaml

## Actual Behavior
A PHP file is necessary. 

Proposal:
```
version: '1'
deployment:
  options:
    initialDeployment: false
  apps:
    typo3:
      type: 'TYPO3\\Surf\\Application\\TYPO3\CMS'
      context: 'Production'
      deploymentPath: '/var/www/virtual/project/_domain.tld'
      nodes:
      - my-node
      options:
        projectName: ''
        repositoryUrl: ''
        branch: ''

nodes:
  my-node:
    hostname: ''
    port: 22
    user: abc
```
